-- This table links a course to its primary tutor.
-- A course can have only one primary tutor.
-- A tutor can be the primary tutor for multiple courses.

CREATE TABLE public.course_tutors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id UUID NOT NULL UNIQUE REFERENCES public.academy_courses(id) ON DELETE CASCADE,
    tutor_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Add a trigger to automatically update the `updated_at` timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_course_tutors_updated
BEFORE UPDATE ON public.course_tutors
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- Enable RLS
ALTER TABLE public.course_tutors ENABLE ROW LEVEL SECURITY;

-- Policies
-- Admins can do everything
CREATE POLICY "Allow all access to admins"
ON public.course_tutors
FOR ALL
USING (
  (SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true
);

-- Authenticated users can read
CREATE POLICY "Allow read access to authenticated users"
ON public.course_tutors
FOR SELECT
USING (
  auth.role() = 'authenticated'
);
